dirs:
  saved_models: ./saved_model

training:
  loss: 'categorical_crossentropy'
  optimizer: 'adam'
  metrics: [ 'accuracy' ]

pamap2:
  epochs: 3
  batch_size: 128
  d_model: 128
  dropout: 0.2
  n_head: 4

skoda:
  epochs: 10
  batch_size: 256
  d_model: 128

opp:
  epochs: 1
  batch_size: 256
  d_model: 128
  n_head: 4

uschad:
  epochs: 1
  batch_size: 256
  d_model: 128
  n_head: 4
